/* eslint-disable no-undef */
/**
 * Hexo server middleware — wires LaikaCMS into Hexo's dev server.
 *
 * Hexo 8 supports ESM scripts when the file extension is .mjs.
 * This script is loaded automatically by Hexo from the scripts/ directory.
 *
 * Integration pattern:
 *   1. LaikaCMS is configured with contentDir = source/ and collection folder = _posts/,
 *      so it writes/reads from source/_posts/ — exactly where Hexo reads posts.
 *   2. The middleware intercepts /api/decap/* and bridges Hexo's Node.js
 *      IncomingMessage to the WHATWG Request that laika.fetch expects.
 *   3. /admin returns the Decap admin shell (generated by decapAdminHtml()).
 *
 * Doc gap: ESM/CJS interop.
 *   Hexo scripts are CJS by default. Rename to .mjs (Hexo 8+) to load as ESM.
 *   LaikaCMS packages are ESM-only, so CJS require() won't work — .mjs is required.
 *
 * Doc gap: contentDir vs. collection folder.
 *   createEmbeddedLaika writes config.yml to <contentDir>/config.yml.
 *   Setting contentDir = 'source' and folder = '_posts' makes Laika write posts
 *   to source/_posts/, matching Hexo's expectation. Hexo ignores config.yml (YAML,
 *   not Markdown) so there is no conflict.
 *
 * Doc gap: date format.
 *   Decap's datetime widget emits ISO 8601 (e.g. "2024-01-15T12:00:00.000Z").
 *   Hexo displays dates with its own date_format from _config.yml and parses
 *   ISO 8601 correctly via moment.js. No conversion needed.
 */
import { resolve } from 'node:path';

import { createEmbeddedLaika, decapAdminHtml } from '@laikacms/decap-integrations/embedded';

const hexoDir = hexo.base_dir; // Hexo injects `hexo` global into all scripts.

const decapConfig = {
  backend: { name: 'laika', api_url: '/api/decap' },
  media_folder: 'source/images',
  public_folder: '/images',
  collections: [
    {
      name: 'posts',
      label: 'Blog Posts',
      folder: '_posts', // relative to contentDir (source/), so → source/_posts/
      create: true,
      slug: '{{slug}}',
      sortable_fields: ['title', 'date'],
      fields: [
        { label: 'Title', name: 'title', widget: 'string' },
        { label: 'Date', name: 'date', widget: 'datetime' },
        { label: 'Description', name: 'description', widget: 'string', required: false },
        { label: 'Body', name: 'body', widget: 'markdown' },
      ],
    },
  ],
};

const laika = createEmbeddedLaika({
  contentDir: resolve(hexoDir, 'source'),
  decapConfig,
  basePath: '/api/decap',
  auth: { mode: 'dev' },
});

const ADMIN_HTML = decapAdminHtml({
  decapConfig,
  title: 'Admin · LaikaCMS Hexo starter',
});

/**
 * Convert a Node.js IncomingMessage to a WHATWG Fetch Request.
 *
 * This is the same bridge pattern used by starter-express-blog,
 * starter-koa-blog, and starter-eleventy-blog.
 *
 * @param {import('http').IncomingMessage} req
 * @returns {Promise<Request>}
 */
async function toLaikaRequest(req) {
  const host = req.headers['host'] ?? 'localhost:4000';
  const url = new URL(req.url ?? '/', `http://${host}`);

  let body;
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    const chunks = [];
    for await (const chunk of req) chunks.push(Buffer.from(chunk));
    const buf = Buffer.concat(chunks);
    if (buf.byteLength > 0) {
      body = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
    }
  }

  return new Request(url.toString(), {
    method: req.method ?? 'GET',
    headers: Object.fromEntries(
      Object.entries(req.headers).filter(([, v]) => typeof v === 'string'),
    ),
    body,
  });
}

/**
 * Hexo server middleware filter.
 * Intercepts /api/decap/* and /admin before Hexo's own request handling.
 *
 * @param {import('connect').Server} app
 */
hexo.extend.filter.register('server_middleware', app => {
  // Decap JSON:API proxy — all methods forwarded to laika.fetch.
  app.use('/api/decap', async (req, res, _next) => {
    try {
      const webReq = await toLaikaRequest(req);
      const webRes = await laika.fetch(webReq);

      res.statusCode = webRes.status;
      webRes.headers.forEach((value, name) => {
        if (name.toLowerCase() !== 'transfer-encoding') res.setHeader(name, value);
      });
      res.end(Buffer.from(await webRes.arrayBuffer()));
    } catch (err) {
      console.error('[laika] API error:', err);
      if (!res.headersSent) {
        res.statusCode = 500;
        res.end('Internal Server Error');
      }
    }
  });

  // Decap admin shell — generated without a build step.
  app.use('/admin', (req, res, _next) => {
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.end(ADMIN_HTML);
  });
});
