export declare const CMS_BRANCH_PREFIX = "cms";
export declare const DEFAULT_PR_BODY = "Automatically generated by Decap CMS";
export declare const MERGE_COMMIT_MESSAGE = "Automatically generated. Merged on Decap CMS.";
export declare function isCMSLabel(label: string, labelPrefix: string): boolean;
export declare function labelToStatus(label: string, labelPrefix: string): string;
export declare function statusToLabel(status: string, labelPrefix: string): string;
export declare function generateContentKey(collectionName: string, slug: string): string;
export declare function parseContentKey(contentKey: string): {
    collection: string;
    slug: string;
};
export declare function contentKeyFromBranch(branch: string): string;
export declare function branchFromContentKey(contentKey: string): string;
