import APIError from './APIError';
import Cursor, { CURSOR_COMPATIBILITY_SYMBOL } from './Cursor';
import EditorialWorkflowError, { EDITORIAL_WORKFLOW_ERROR } from './EditorialWorkflowError';
import AccessTokenError from './AccessTokenError';
import localForage from './localForage';
import { isAbsolutePath, basename, fileExtensionWithSeparator, fileExtension } from './path';
import { onlySuccessfulPromises, flowAsync, then } from './promise';
import unsentRequest from './unsentRequest';
import { filterByExtension, getAllResponses, parseLinkHeader, parseResponse, responseParser, getPathDepth } from './backendUtil';
import loadScript from './loadScript';
import getBlobSHA from './getBlobSHA';
import { asyncLock } from './asyncLock';
import { entriesByFiles, entriesByFolder, unpublishedEntries, getMediaDisplayURL, getMediaAsBlob, runWithLock, blobToFileObj, allEntriesByFolder } from './implementation';
import { readFile, readFileMetadata, isPreviewContext, getPreviewStatus, PreviewState, requestWithBackoff, getDefaultBranchName, throwOnConflictingBranches } from './API';
import { CMS_BRANCH_PREFIX, generateContentKey, isCMSLabel, labelToStatus, statusToLabel, DEFAULT_PR_BODY, MERGE_COMMIT_MESSAGE, parseContentKey, branchFromContentKey, contentKeyFromBranch } from './APIUtils';
import { createPointerFile, getLargeMediaFilteredMediaFiles, getLargeMediaPatternsFromGitAttributesFile, parsePointerFile, getPointerFileForMediaFileObj } from './git-lfs';
import type { PointerFile as PF } from './git-lfs';
import type { FetchError as FE, ApiRequest as AR } from './API';
import type { Implementation as I, ImplementationEntry as IE, UnpublishedEntryDiff as UED, UnpublishedEntry as UE, ImplementationMediaFile as IMF, ImplementationFile as IF, DisplayURLObject as DUO, DisplayURL as DU, Credentials as Cred, User as U, Entry as E, PersistOptions as PO, AssetProxy as AP, Config as C, UnpublishedEntryMediaFile as UEMF, DataFile as DF } from './implementation';
import type { AsyncLock as AL } from './asyncLock';
export type AsyncLock = AL;
export type Implementation = I;
export type ImplementationEntry = IE;
export type UnpublishedEntryDiff = UED;
export type UnpublishedEntry = UE;
export type ImplementationMediaFile = IMF;
export type ImplementationFile = IF;
export type DisplayURL = DU;
export type DisplayURLObject = DUO;
export type Credentials = Cred;
export type User = U;
export type Entry = E;
export type UnpublishedEntryMediaFile = UEMF;
export type PersistOptions = PO;
export type AssetProxy = AP;
export type ApiRequest = AR;
export type Config = C;
export type FetchError = FE;
export type PointerFile = PF;
export type DataFile = DF;
export declare const DecapCmsLibUtil: {
    APIError: typeof APIError;
    Cursor: typeof Cursor;
    CURSOR_COMPATIBILITY_SYMBOL: symbol;
    EditorialWorkflowError: typeof EditorialWorkflowError;
    EDITORIAL_WORKFLOW_ERROR: string;
    localForage: LocalForage;
    basename: typeof basename;
    fileExtensionWithSeparator: typeof fileExtensionWithSeparator;
    fileExtension: typeof fileExtension;
    onlySuccessfulPromises: typeof onlySuccessfulPromises;
    flowAsync: typeof flowAsync;
    then: typeof then;
    unsentRequest: {
        toURL: (req: any) => string;
        fromURL: (wholeURL: any) => import("immutable").Map<string, any>;
        fromFetchArguments: (wholeURL: any, options: any) => import("immutable").Map<string, any>;
        performRequest: (req: any) => any;
        withMethod: any;
        withBody: any;
        withHeaders: any;
        withParams: any;
        withRoot: any;
        withNoCache: any;
        fetchWithTimeout: (input: any, init: any) => Promise<Response>;
    };
    filterByExtension: typeof filterByExtension;
    parseLinkHeader: typeof parseLinkHeader;
    parseResponse: typeof parseResponse;
    responseParser: typeof responseParser;
    loadScript: typeof loadScript;
    getBlobSHA: (blob: Blob) => Promise<string>;
    getPathDepth: typeof getPathDepth;
    entriesByFiles: typeof entriesByFiles;
    entriesByFolder: typeof entriesByFolder;
    unpublishedEntries: typeof unpublishedEntries;
    getMediaDisplayURL: typeof getMediaDisplayURL;
    getMediaAsBlob: typeof getMediaAsBlob;
    readFile: typeof readFile;
    readFileMetadata: typeof readFileMetadata;
    CMS_BRANCH_PREFIX: string;
    generateContentKey: typeof generateContentKey;
    isCMSLabel: typeof isCMSLabel;
    labelToStatus: typeof labelToStatus;
    statusToLabel: typeof statusToLabel;
    DEFAULT_PR_BODY: string;
    MERGE_COMMIT_MESSAGE: string;
    isPreviewContext: typeof isPreviewContext;
    getPreviewStatus: typeof getPreviewStatus;
    runWithLock: typeof runWithLock;
    PreviewState: typeof PreviewState;
    parseContentKey: typeof parseContentKey;
    createPointerFile: typeof createPointerFile;
    getLargeMediaFilteredMediaFiles: typeof getLargeMediaFilteredMediaFiles;
    getLargeMediaPatternsFromGitAttributesFile: (...args: any[]) => any;
    parsePointerFile: (data: string) => PF;
    getPointerFileForMediaFileObj: typeof getPointerFileForMediaFileObj;
    branchFromContentKey: typeof branchFromContentKey;
    contentKeyFromBranch: typeof contentKeyFromBranch;
    blobToFileObj: typeof blobToFileObj;
    requestWithBackoff: typeof requestWithBackoff;
    getDefaultBranchName: typeof getDefaultBranchName;
    allEntriesByFolder: typeof allEntriesByFolder;
    AccessTokenError: typeof AccessTokenError;
    throwOnConflictingBranches: typeof throwOnConflictingBranches;
};
export { APIError, Cursor, CURSOR_COMPATIBILITY_SYMBOL, EditorialWorkflowError, EDITORIAL_WORKFLOW_ERROR, localForage, basename, fileExtensionWithSeparator, fileExtension, onlySuccessfulPromises, flowAsync, then, unsentRequest, filterByExtension, parseLinkHeader, getAllResponses, parseResponse, responseParser, loadScript, getBlobSHA, asyncLock, isAbsolutePath, getPathDepth, entriesByFiles, entriesByFolder, unpublishedEntries, getMediaDisplayURL, getMediaAsBlob, readFile, readFileMetadata, CMS_BRANCH_PREFIX, generateContentKey, isCMSLabel, labelToStatus, statusToLabel, DEFAULT_PR_BODY, MERGE_COMMIT_MESSAGE, isPreviewContext, getPreviewStatus, runWithLock, PreviewState, parseContentKey, createPointerFile, getLargeMediaFilteredMediaFiles, getLargeMediaPatternsFromGitAttributesFile, parsePointerFile, getPointerFileForMediaFileObj, branchFromContentKey, contentKeyFromBranch, blobToFileObj, requestWithBackoff, getDefaultBranchName, allEntriesByFolder, AccessTokenError, throwOnConflictingBranches, };
