/**
 * Browser-side admin bundle entry point.
 *
 * Bundled by esbuild (pnpm build:admin):
 *   src/admin-client.ts → public/admin/bundle.js
 *
 * The bare, non-laika Decap app and every registration (backends, widgets,
 * locales) come from src/cms.ts — generated by the `laika create` wizard.
 * This entry supplies the site's config and explicitly mounts the bare app.
 */
import { init } from './cms.js';
import { blogCollections } from './decap-config.js';

init({
  config: {
    // The complete config is inline; do not also fetch /admin/config.yml.
    load_config_file: false,
    backend: { name: 'laika', api_url: '/api/decap' },
    media_folder: 'public/uploads',
    public_folder: '/uploads',
    collections: blogCollections,
  } as any,
});
