/**
 * Multi-collection portfolio site — Hono + LaikaCMS.
 *
 * Most LaikaCMS starters use a single "posts" collection, but real CMSes
 * manage multiple content types. This starter shows:
 *
 *   1. Building a full decapConfig with three collections (posts, projects,
 *      pages) instead of using minimalBlogConfig().
 *
 *   2. Querying each collection with laika.documents.listRecordSummaries({
 *        folder: 'posts' | 'projects' | 'pages', ...
 *      }) — the `folder` parameter maps to the Decap collection's `folder`
 *      field (a subdirectory of contentDir).
 *
 *   3. Using the `fields` schema in decapConfig to get structured content:
 *      posts have markdown body, projects have a tech stack list + URL,
 *      pages are singleton-style (one file per page).
 *
 * Doc gap surfaced: minimalBlogConfig() creates a single "posts" collection.
 * The docs don't prominently show how to extend to multiple collections or
 * how the `folder` value in the config maps to the filesystem layout and to
 * the `folder` parameter of listRecordSummaries.
 *
 * Filesystem layout (under contentDir):
 *   posts/      ← blog posts (Markdown with frontmatter)
 *   projects/   ← portfolio projects
 *   pages/      ← static pages (about.md, contact.md, etc.)
 *   config.yml  ← generated by createEmbeddedLaika from decapConfig
 */
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

import { serve } from '@hono/node-server';
import { createEmbeddedLaika, decapAdminHtml } from '@laikacms/decap-integrations/embedded';
import { Hono } from 'hono';
import { collectStream, runTask } from 'laikacms/compat';
import { NotFoundError } from 'laikacms/core';

const PORT = Number(process.env['PORT'] ?? 3000);
const CONTENT_DIR = resolve(process.env['CONTENT_DIR'] ?? './content');

mkdirSync(CONTENT_DIR, { recursive: true });

// Full multi-collection decapConfig — minimalBlogConfig() only creates one
// collection. Real apps need to define collections manually.
const decapConfig = {
  backend: { name: 'laika', api_url: '/api/decap' },
  media_folder: 'public/uploads',
  public_folder: '/uploads',
  collections: [
    {
      name: 'posts',
      label: 'Blog Posts',
      folder: 'posts',
      create: true,
      slug: '{{slug}}',
      sortable_fields: ['title', 'date'],
      fields: [
        { label: 'Title', name: 'title', widget: 'string' },
        { label: 'Date', name: 'date', widget: 'datetime' },
        { label: 'Description', name: 'description', widget: 'string', required: false },
        { label: 'Body', name: 'body', widget: 'markdown' },
      ],
    },
    {
      name: 'projects',
      label: 'Projects',
      folder: 'projects',
      create: true,
      slug: '{{slug}}',
      sortable_fields: ['title'],
      fields: [
        { label: 'Name', name: 'title', widget: 'string' },
        { label: 'Description', name: 'description', widget: 'markdown' },
        { label: 'Tech Stack', name: 'stack', widget: 'list' },
        { label: 'Live URL', name: 'url', widget: 'string', required: false },
        { label: 'GitHub URL', name: 'github', widget: 'string', required: false },
      ],
    },
    {
      name: 'pages',
      label: 'Pages',
      folder: 'pages',
      create: true,
      slug: '{{slug}}',
      fields: [
        { label: 'Title', name: 'title', widget: 'string' },
        { label: 'Body', name: 'body', widget: 'markdown' },
      ],
    },
  ],
};

const laika = createEmbeddedLaika({
  contentDir: CONTENT_DIR,
  decapConfig,
  basePath: '/api/decap',
  auth: { mode: 'dev' },
});

const ADMIN_HTML = decapAdminHtml({
  decapConfig,
  title: 'Admin · Portfolio CMS',
});

// --- Type helpers ---

interface RecordSummary {
  type: string;
  key: string;
  updatedAt?: string;
}

interface PostContent {
  title?: string;
  date?: string;
  description?: string;
  body?: string;
}

interface ProjectContent {
  title?: string;
  description?: string;
  stack?: string[];
  url?: string;
  github?: string;
}

interface PageContent {
  title?: string;
  body?: string;
}

// --- Routes ---

const app = new Hono();

app.get('/health', c => c.json({ status: 'ok' }));

// Site index — latest 5 posts + project count + page links
app.get('/', async c => {
  const [postsStream, projectsStream, pagesStream] = await Promise.all([
    collectStream(
      laika.documents.listRecordSummaries({
        pagination: { page: 1, perPage: 5 },
        folder: 'posts',
        depth: 1,
        type: 'published',
      }),
    ),
    collectStream(
      laika.documents.listRecordSummaries({
        pagination: { page: 1, perPage: 100 },
        folder: 'projects',
        depth: 1,
        type: 'published',
      }),
    ),
    collectStream(
      laika.documents.listRecordSummaries({
        pagination: { page: 1, perPage: 100 },
        folder: 'pages',
        depth: 1,
        type: 'published',
      }),
    ),
  ]);

  const posts = (postsStream.items as RecordSummary[]).filter(r => r.type === 'published-summary');
  const projects = (projectsStream.items as RecordSummary[]).filter(r => r.type === 'published-summary');
  const pages = (pagesStream.items as RecordSummary[]).filter(r => r.type === 'published-summary');

  const postLinks = posts.length === 0
    ? `<p style="color:#666">No posts yet.</p>`
    : posts
      .sort((a, b) => (b.updatedAt ?? '').localeCompare(a.updatedAt ?? ''))
      .map(r => {
        const slug = r.key.replace(/^posts\//, '').replace(/\.md$/, '');
        return `<li><a href="/blog/${slug}">${slug}</a></li>`;
      })
      .join('');

  const projectLinks = projects.length === 0
    ? `<p style="color:#666">No projects yet.</p>`
    : projects
      .map(r => {
        const slug = r.key.replace(/^projects\//, '').replace(/\.md$/, '');
        return `<li><a href="/projects/${slug}">${slug}</a></li>`;
      })
      .join('');

  const pageLinks = pages.length === 0
    ? ''
    : `<ul>${
      pages
        .map(r => {
          const slug = r.key.replace(/^pages\//, '').replace(/\.md$/, '');
          return `<li><a href="/pages/${slug}">${slug}</a></li>`;
        })
        .join('')
    }</ul>`;

  return c.html(`<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>Portfolio</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px}
a{color:#0070f3}nav{display:flex;gap:16px;border-bottom:1px solid #eee;padding-bottom:12px;margin-bottom:32px}
section{margin-bottom:32px}h2{margin-bottom:8px}</style>
</head><body>
<nav>
  <strong>Portfolio</strong>
  <a href="/blog">Blog</a>
  <a href="/projects">Projects</a>
  ${pageLinks}
  <span style="flex:1"></span>
  <a href="/admin">CMS ↗</a>
</nav>
<section>
  <h2>Latest Posts</h2>
  <ul>${postLinks}</ul>
  <p><a href="/blog">All posts →</a></p>
</section>
<section>
  <h2>Projects</h2>
  <ul>${projectLinks}</ul>
</section>
</body></html>`);
});

// Blog index
app.get('/blog', async c => {
  const { items } = await collectStream(
    laika.documents.listRecordSummaries({
      pagination: { page: 1, perPage: 100 },
      folder: 'posts',
      depth: 1,
      type: 'published',
    }),
  );
  const posts = (items as RecordSummary[])
    .filter(r => r.type === 'published-summary')
    .sort((a, b) => (b.updatedAt ?? '').localeCompare(a.updatedAt ?? ''));
  const listHtml = posts.length === 0
    ? `<p>No posts yet. <a href="/admin">Write the first one.</a></p>`
    : `<ul>${
      posts.map(r => {
        const slug = r.key.replace(/^posts\//, '').replace(/\.md$/, '');
        return `<li><a href="/blog/${slug}">${slug}</a></li>`;
      }).join('')
    }</ul>`;
  return c.html(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Blog</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px}a{color:#0070f3}</style>
</head><body><p><a href="/">← Home</a></p><h1>Blog</h1>${listHtml}</body></html>`);
});

// Single post
app.get('/blog/:slug', async c => {
  const slug = c.req.param('slug');
  try {
    const doc = await runTask(laika.documents.getDocument(`posts/${slug}.md`));
    const { title, body } = doc.content as PostContent;
    return c.html(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${title ?? slug}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px}a{color:#0070f3}</style>
</head><body><p><a href="/blog">← Blog</a></p><h1>${title ?? slug}</h1><article>${body ?? ''}</article></body></html>`);
  } catch (err) {
    if (err instanceof NotFoundError) {
      c.status(404);
      return c.html('<h1>Post not found</h1>');
    }
    throw err;
  }
});

// Projects index
app.get('/projects', async c => {
  const { items } = await collectStream(
    laika.documents.listRecordSummaries({
      pagination: { page: 1, perPage: 100 },
      folder: 'projects',
      depth: 1,
      type: 'published',
    }),
  );
  const projects = (items as RecordSummary[]).filter(r => r.type === 'published-summary');
  const listHtml = projects.length === 0
    ? `<p>No projects yet. <a href="/admin">Add the first one.</a></p>`
    : `<ul>${
      projects.map(r => {
        const slug = r.key.replace(/^projects\//, '').replace(/\.md$/, '');
        return `<li><a href="/projects/${slug}">${slug}</a></li>`;
      }).join('')
    }</ul>`;
  return c.html(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Projects</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px}a{color:#0070f3}</style>
</head><body><p><a href="/">← Home</a></p><h1>Projects</h1>${listHtml}</body></html>`);
});

// Single project
app.get('/projects/:slug', async c => {
  const slug = c.req.param('slug');
  try {
    const doc = await runTask(laika.documents.getDocument(`projects/${slug}.md`));
    const { title, description, stack = [], url, github } = doc.content as ProjectContent;
    const stackHtml = stack.length > 0
      ? `<p><strong>Stack:</strong> ${stack.map(s => `<code>${s}</code>`).join(' ')}</p>`
      : '';
    const links = [
      url ? `<a href="${url}">Live →</a>` : '',
      github ? `<a href="${github}">GitHub →</a>` : '',
    ].filter(Boolean).join(' · ');
    return c.html(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${title ?? slug}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px}a{color:#0070f3}code{background:#f1f5f9;padding:2px 6px;border-radius:4px}</style>
</head><body><p><a href="/projects">← Projects</a></p><h1>${title ?? slug}</h1>${stackHtml}${
      links ? `<p>${links}</p>` : ''
    }<article>${description ?? ''}</article></body></html>`);
  } catch (err) {
    if (err instanceof NotFoundError) {
      c.status(404);
      return c.html('<h1>Project not found</h1>');
    }
    throw err;
  }
});

// Static pages (about, contact, etc.)
app.get('/pages/:slug', async c => {
  const slug = c.req.param('slug');
  try {
    const doc = await runTask(laika.documents.getDocument(`pages/${slug}.md`));
    const { title, body } = doc.content as PageContent;
    return c.html(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${title ?? slug}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px}a{color:#0070f3}</style>
</head><body><p><a href="/">← Home</a></p><h1>${title ?? slug}</h1><article>${body ?? ''}</article></body></html>`);
  } catch (err) {
    if (err instanceof NotFoundError) {
      c.status(404);
      return c.html('<h1>Page not found</h1>');
    }
    throw err;
  }
});

app.get('/admin', c => c.html(ADMIN_HTML));
app.all('/api/decap/*', c => laika.fetch(c.req.raw));

serve({ fetch: app.fetch, port: PORT, hostname: '0.0.0.0' }, info => {
  // eslint-disable-next-line no-console
  console.log(`\nPortfolio CMS running at http://localhost:${info.port}`);
  // eslint-disable-next-line no-console
  console.log(`  Content: ${CONTENT_DIR}`);
});
