/**
 * JSON Schema → TypeScript source, for Astro's `Loader.createSchema()`.
 *
 * A schema read from a CMS config at build time is invisible to the type
 * checker, so a derived schema would normally cost you `entry.data.title` and
 * leave `data` as `unknown`. Astro's answer is `createSchema()`: return the
 * runtime schema *and* the TypeScript source describing it, and Astro writes
 * that source into `.astro/loaders/<collection>.ts` and types entries from it.
 *
 * This module is that second half. It mirrors `jsonSchemaToZod` field for field
 * — the two must agree, or the checker would promise a shape validation does not
 * enforce. Anything unrecognised becomes `unknown`, matching the permissive
 * branch on the Zod side.
 */

import type { JSONSchema7, JSONSchema7Definition, JSONSchema7TypeName } from 'json-schema';

/** The type name Astro imports from the generated module. */
export const ENTRY_TYPE_NAME = 'Entry';

/**
 * Wrap a rendered type body in the module Astro expects back from
 * `createSchema()`.
 *
 * Astro writes this source to `.astro/loaders/<collection>.ts` itself and types
 * entries as `import("./loaders/<collection>.js").Entry` — this package never
 * writes it. Both type sources (the catalog schema and content inference) come
 * through here so the two produce identically-shaped modules.
 */
export function renderEntryModule(
  body: string,
  options: { collection?: string, source: 'catalog' | 'content' },
): string {
  const origin = options.source === 'catalog'
    ? 'the Laika catalog — do not edit; change your CMS config instead'
    : 'the content itself — do not edit; it follows whatever the content contains';
  const scope = options.collection === undefined ? '' : ` for the "${options.collection}" collection`;
  return `// Generated by @laikacms/astro from ${origin}.\n`
    + `// Source${scope}: ${options.source}.\n`
    + `export type ${ENTRY_TYPE_NAME} = ${body};\n`;
}

/**
 * How a `date` / `date-time` string is typed.
 *
 * `'Date'` is only honest where something coerces it. The build-time path runs
 * the Zod schema from `jsonSchemaToZod`, which does; the live path reads the
 * repository and hands back whatever the serializer produced — a string from
 * JSON, possibly a `Date` from YAML front matter — so it gets the union and the
 * template is forced to handle both.
 */
export type DateType = 'Date' | 'string | Date';

export interface TypeRenderOptions {
  /** Defaults to `'Date'`. */
  dateType?: DateType;
  /** Indentation level of the outermost `{`. Defaults to `0`. */
  depth?: number;
}

/**
 * Render a collection's JSON Schema as a TypeScript module exporting
 * {@link ENTRY_TYPE_NAME}.
 */
export function jsonSchemaToTypeScript(schema: JSONSchema7, collection?: string): string {
  return renderEntryModule(render(schema, 0, 'Date'), {
    ...(collection !== undefined ? { collection } : {}),
    source: 'catalog',
  });
}

/**
 * Render a JSON Schema as a bare TypeScript type expression.
 *
 * The module-wrapping in {@link jsonSchemaToTypeScript} is what `createSchema()`
 * wants; the live-collection types are members of one generated interface
 * instead, so they need the expression on its own.
 */
export function jsonSchemaToTypeExpression(
  schema: JSONSchema7,
  options: TypeRenderOptions = {},
): string {
  return render(schema, options.depth ?? 0, options.dateType ?? 'Date');
}

function render(schema: JSONSchema7Definition | undefined, depth: number, dates: DateType): string {
  if (schema === undefined || typeof schema === 'boolean') return 'unknown';

  // A variable-type list's items. Checked before `type` because such a schema
  // has none of its own, and must match the `anyOf` branch in jsonSchemaToZod.
  if (Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
    const members = [...new Set(schema.anyOf.map(one => render(one, depth, dates)))];
    return members.length > 1 ? members.join(' | ') : members[0] ?? 'unknown';
  }

  if (Array.isArray(schema.enum) && schema.enum.length > 0) return renderEnum(schema.enum);

  const type = schema.type;
  if (type === undefined) return 'unknown';
  if (Array.isArray(type)) {
    const members = [...new Set(type.map(one => renderScalar(one, schema, depth, dates)))];
    return members.length > 1 ? members.join(' | ') : members[0] ?? 'unknown';
  }
  return renderScalar(type, schema, depth, dates);
}

function renderScalar(
  type: JSONSchema7TypeName,
  schema: JSONSchema7,
  depth: number,
  dates: DateType,
): string {
  switch (type) {
    case 'string':
      // Must match jsonSchemaToZod, which coerces these two formats to a Date.
      return schema.format === 'date' || schema.format === 'date-time' ? dates : 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      // A union element needs parenthesising: `Array<A | B>` is fine, but the
      // members are rendered independently and `A | B[]` would parse as
      // `A | (B[])` if this ever switched to postfix syntax. Keeping `Array<>`
      // makes that safe by construction.
      return `Array<${render(itemSchema(schema.items), depth, dates)}>`;
    case 'object':
      return renderObject(schema, depth, dates);
    default:
      return 'unknown';
  }
}

function renderObject(schema: JSONSchema7, depth: number, dates: DateType): string {
  const properties = schema.properties;
  if (properties === undefined) return 'unknown';

  const entries = Object.entries(properties);
  if (entries.length === 0) return 'Record<string, unknown>';

  const required = new Set(schema.required ?? []);
  const indent = '  '.repeat(depth + 1);
  const closing = '  '.repeat(depth);

  const lines = entries.map(([name, property]) => {
    const optional = required.has(name) ? '' : '?';
    return `${indent}${propertyName(name)}${optional}: ${render(property, depth + 1, dates)};`;
  });

  return `{\n${lines.join('\n')}\n${closing}}`;
}

/** Quote a key that is not a valid bare identifier. */
function propertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function renderEnum(values: readonly unknown[]): string {
  const strings = values.filter((value): value is string => typeof value === 'string');
  // A mixed-type enum falls back to `unknown` on the Zod side; the two must
  // agree or the checker would promise more than validation delivers.
  if (strings.length !== values.length || strings.length === 0) return 'unknown';
  return strings.map(value => JSON.stringify(value)).join(' | ');
}

function itemSchema(items: JSONSchema7['items']): JSONSchema7Definition | undefined {
  if (items === undefined || Array.isArray(items)) return undefined;
  return items;
}
