/**
 * CMS registration module — generated by the `laika create` wizard, then
 * adapted for this starter: the `laika` backend is created with *injected*
 * repositories (`createLaikaBackend({ getDocumentsRepository, getAssetsRepository })`),
 * so every entry and media operation runs against the in-browser
 * `WebFsStorageRepository` from `src/storage.ts` instead of a JSON:API proxy.
 *
 * Boots the bare, non-laika Decap app (`@laikacms/decap-cms/app/bare`), which
 * ships with no backends, widgets, or locales; everything the admin
 * uses is registered explicitly below. Re-run the wizard or edit this file
 * to change the selection. English is always registered as the fallback.
 */
import './prism-global.js';
// TODO(app/bare): the published @laikacms/decap-cms does not export the
// bare, non-laika app yet — until it does, boot the laika-styled bare app,
// which has the same init/CMS registration surface. Swap back to
//   import { DecapCmsApp as CMS, init } from '@laikacms/decap-cms/app/bare';
// once `./app/bare` ships.
import { CMS, init } from '@laikacms/decap-cms/laika-app/bare';
import en from '@laikacms/decap-cms/locales/en';

import createLaikaBackend from '@laikacms/decap-cms/backends/laika';
import { jsonEntryCodec } from '@laikacms/decap-cms/entry-codecs/json';
import DecapCmsWidgetString from '@laikacms/decap-cms/widgets/string';
import DecapCmsWidgetDatetime from '@laikacms/decap-cms/widgets/datetime';
import { markdownFormat } from '@laikacms/decap-cms/format-packs/markdown';
import { passthroughSerializer, Widget as RichtextWidget } from '@laikacms/decap-cms/widgets/richtext';

import { getRepositories } from './storage.js';

CMS.registerLocale('en', en);

CMS.registerBackend('laika', createLaikaBackend({
  getDocumentsRepository: () => getRepositories().documents,
  getAssetsRepository: () => getRepositories().assets,
}));

// The bare app registers no entry codecs, but folder collections resolve
// their file format against the registry. The laika backend supports JSON
// collections only (entries are already objects), so the identity codec is
// the one to register — every collection sets `format: 'json'`.
CMS.registerEntryCodec(jsonEntryCodec);

CMS.registerWidget(DecapCmsWidgetString.Widget());
CMS.registerWidget(DecapCmsWidgetDatetime.Widget());
// Spread: interfaces lack the implicit index signature registerWidget expects
const richtextWidget = { ...RichtextWidget() };
CMS.registerWidget(richtextWidget);
CMS.registerWidget({ ...richtextWidget, name: 'markdown' });
CMS.registerWidgetValueSerializer('richtext', passthroughSerializer);
CMS.registerWidgetValueSerializer('markdown', passthroughSerializer);
CMS.registerRichtextFormat(markdownFormat);

export { CMS, init };
