import { List } from 'immutable';
import type { Collection, Collections, EntryField, EntryMap, ViewFilter, ViewGroup, CmsConfig } from '../types/redux';
import type { ConfigAction } from '../actions/config';
import type { Backend } from '../backend';
declare function collections(state: Collections, action: ConfigAction): any;
export declare function getFileFromSlug(collection: Collection, slug: string): any;
export declare function selectFieldsWithMediaFolders(collection: Collection, slug: string): EntryField[];
export declare function selectMediaFolders(config: CmsConfig, collection: Collection, entry: EntryMap): any;
export declare function selectFields(collection: Collection, slug: string): any;
export declare function selectFolderEntryExtension(collection: Collection): any;
export declare function selectFileEntryLabel(collection: Collection, slug: string): any;
export declare function selectEntryPath(collection: Collection, slug: string): any;
export declare function selectEntrySlug(collection: Collection, path: string): any;
export declare function selectAllowNewEntries(collection: Collection): boolean;
export declare function selectAllowDeletion(collection: Collection): boolean;
export declare function selectTemplateName(collection: Collection, slug: string): string;
export declare function getFieldsNames(fields: EntryField[], prefix?: string): string[];
export declare function selectField(collection: Collection, key: string): any;
export declare function traverseFields(fields: List<EntryField>, updater: (field: EntryField) => EntryField, done?: () => boolean): List<EntryField>;
export declare function updateFieldByKey(collection: Collection, key: string, updater: (field: EntryField) => EntryField): Collection;
export declare function selectIdentifier(collection: Collection): any;
export declare function selectInferredField(collection: Collection, fieldName: string): any;
export declare function selectEntryCollectionTitle(collection: Collection, entry: EntryMap): any;
export declare function selectDefaultSortableFields(collection: Collection, backend: Backend, hasIntegration: boolean): {
    field: string;
    label?: string;
    default_sort?: boolean | "asc" | "desc";
}[];
export declare function selectSortableFields(collection: Collection, t: (key: string) => string): any;
export declare function selectDefaultSortField(collection: Collection): {
    field: any;
    direction: any;
};
export declare function selectSortDataPath(collection: Collection, key: string): string;
export declare function selectViewFilters(collection: Collection): ViewFilter[];
export declare function selectViewGroups(collection: Collection): ViewGroup[];
export declare function selectFieldsComments(collection: Collection, entryMap: EntryMap): Record<string, string>;
export declare function selectHasMetaPath(collection: Collection): boolean;
export default collections;
