import type { EntriesAction, Entries, CmsConfig, Collection, EntryDraft, EntryMap, EntryField, GroupOfEntries } from '../types/redux';
declare function entries(state: any, action: EntriesAction): any;
export declare function selectEntriesSort(entries: Entries, collection: string): any;
export declare function selectEntriesFilter(entries: Entries, collection: string): any;
export declare function selectEntriesGroup(entries: Entries, collection: string): any;
export declare function selectEntriesGroupField(entries: Entries, collection: string): any;
export declare function selectEntriesSortFields(entries: Entries, collection: string): any;
export declare function selectEntriesFilterFields(entries: Entries, collection: string): any;
export declare function selectViewStyle(entries: Entries): string;
export declare function selectEntry(state: Entries, collection: string, slug: string): EntryMap;
export declare function selectPublishedSlugs(state: Entries, collection: string): List<string>;
export declare function selectEntries(state: Entries, collection: Collection): any;
export declare function selectGroups(state: Entries, collection: Collection): GroupOfEntries[];
export declare function selectEntryByPath(state: Entries, collection: string, path: string): any;
export declare function selectEntriesLoaded(state: Entries, collection: string): boolean;
export declare function selectIsFetching(state: Entries, collection: string): boolean;
export declare function selectMediaFolder(config: CmsConfig, collection: Collection | null, entryMap: EntryMap | undefined, field: EntryField | undefined): any;
export declare function selectMediaFilePath(config: CmsConfig, collection: Collection | null, entryMap: EntryMap | undefined, mediaPath: string, field: EntryField | undefined): any;
export declare function selectMediaFilePublicPath(config: CmsConfig, collection: Collection | null, mediaPath: string, entryMap: EntryMap | undefined, field: EntryField | undefined): any;
export declare function selectEditingDraft(state: EntryDraft): boolean;
export default entries;
