/**
 * Cloudflare Workers + Hono + D1 blog.
 *
 * Storage: Cloudflare D1 (SQLite) via DrizzleStorageRepository.
 * CMS:     LaikaCMS via createCustomLaika (BYO storage preset).
 * Admin:   Decap CMS shell generated by decapAdminHtml() — loads from CDN.
 *
 * Quick start (local):
 *   pnpm run db:migrate:local   # create the atoms table in local D1
 *   pnpm dev                    # wrangler dev on :3000
 *
 * Deploy:
 *   wrangler d1 create laikacms-d1
 *   # copy database_id to wrangler.toml
 *   pnpm run db:migrate:remote
 *   pnpm deploy
 */
import { createCustomLaika, decapAdminHtml, minimalBlogConfig } from '@laikacms/decap-integrations/custom';
import { Hono } from 'hono';
import { collectStream, runTask } from 'laikacms/compat';
import { NotFoundError } from 'laikacms/core';

import { makeD1Storage } from './db/repo.js';

interface Env {
  DB: D1Database;
}

const decapConfig = minimalBlogConfig();
const adminHtml = decapAdminHtml({ decapConfig });

// Build a Laika instance for each request — D1 binding is per-request, and
// createCustomLaika is a cheap synchronous factory (just object allocations).
function makeLaika(env: Env) {
  return createCustomLaika({
    storage: makeD1Storage(env.DB),
    decapConfig,
    basePath: '/api/decap',
    auth: { mode: 'dev' },
    seedConfigOnFirstRequest: true,
  });
}

const app = new Hono<{ Bindings: Env }>();

// ── Admin shell ───────────────────────────────────────────────────────────────

app.get('/admin', c => c.html(adminHtml));

// ── Laika JSON:API ────────────────────────────────────────────────────────────

app.all('/api/decap/*', c => makeLaika(c.env).fetch(c.req.raw));

// ── Blog home ─────────────────────────────────────────────────────────────────

app.get('/', async c => {
  const laika = makeLaika(c.env);
  const { items: records } = await collectStream(
    laika.documents.listRecordSummaries({
      pagination: { page: 1, perPage: 100 },
      folder: 'posts',
      depth: 1,
      type: 'published',
    }),
  );

  const posts = records
    .filter(r => r.type === 'published-summary')
    .sort((a, b) => {
      if (a.updatedAt && b.updatedAt) return b.updatedAt.localeCompare(a.updatedAt);
      return b.key.localeCompare(a.key);
    });

  const items = posts
    .map(post => {
      const slug = post.key.replace(/^posts\//, '').replace(/\.md$/, '');
      const date = post.updatedAt
        ? ` · <time style="color:#666;font-size:.9em">${new Date(post.updatedAt).toLocaleDateString()}</time>`
        : '';
      return `<li style="margin-bottom:1rem"><a href="/blog/${slug}">${slug}</a>${date}</li>`;
    })
    .join('\n');

  const body = posts.length === 0
    ? '<p>No posts yet. <a href="/admin">Open the CMS</a> to write your first post.</p>'
    : `<ul style="list-style:none;padding:0">${items}</ul>`;

  return c.html(`<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>My Blog (D1)</title></head>
<body>
  <h1>My Blog</h1>
  ${body}
  <p><a href="/admin">Admin →</a></p>
</body>
</html>`);
});

// ── Individual post ───────────────────────────────────────────────────────────

interface PostContent {
  title?: string;
  date?: string;
  description?: string;
  body?: string;
}

app.get('/blog/:slug', async c => {
  const slug = c.req.param('slug');
  const laika = makeLaika(c.env);

  let post;
  try {
    post = await runTask(laika.documents.getDocument(`posts/${slug}`));
  } catch (err) {
    if (err instanceof NotFoundError) return c.notFound();
    throw err;
  }

  const { title, date, description, body } = post.content as PostContent;

  return c.html(`<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>${title ?? slug}</title></head>
<body>
  <article>
    <h1>${title ?? slug}</h1>
    ${date ? `<time style="color:#666">${new Date(date).toLocaleDateString()}</time>` : ''}
    ${description ? `<p><em>${description}</em></p>` : ''}
    <pre style="white-space:pre-wrap;font-family:inherit">${body ?? ''}</pre>
  </article>
  <p><a href="/">← Back</a></p>
</body>
</html>`);
});

export default app;
