/**
 * Hono blog server running on Bun's native HTTP runtime.
 *
 * Key differences from starter-hono-blog (Node.js):
 *   1. No @hono/node-server — Bun supports Hono's fetch handler via Bun.serve()
 *   2. Bun.serve() is WHATWG-native; laika.fetch(c.req.raw) needs zero bridging
 *   3. Static files served with Bun.file() (streaming, no full-buffer read)
 *   4. No admin bundle build step — decapAdminHtml() generates the shell in one call
 *
 * decapAdminHtml() loads Decap CMS and the Laika backend from CDN.
 * No separate src/admin-client.ts or public/admin/index.html needed.
 */
import { join } from 'node:path';

import { decapAdminHtml } from '@laikacms/decap-integrations/embedded';
import { Hono } from 'hono';
import { collectStream, runTask } from 'laikacms/compat';

import { decapConfig, laika } from './laika.js';

const PUBLIC_DIR = join(import.meta.dir, '..', 'public');

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript',
  '.css': 'text/css',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.woff2': 'font/woff2',
};

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function page(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escHtml(title)}</title>
  <style>body{max-width:48rem;margin:0 auto;padding:2rem 1rem;font-family:system-ui,sans-serif}</style>
</head>
<body>
  <nav><a href="/" style="font-weight:bold;text-decoration:none">My Blog</a> · <a href="/admin">CMS</a></nav>
  ${body}
</body>
</html>`;
}

const ADMIN_HTML = decapAdminHtml({
  decapConfig,
  title: 'Admin · LaikaCMS Hono/Bun',
});

const app = new Hono();

// Decap JSON:API — c.req.raw is the WHATWG Request; laika.fetch accepts it directly.
// No IncomingMessage→Request bridge needed (unlike Express, Koa, Fastify on Node.js).
app.all('/api/decap/*', c => laika.fetch(c.req.raw));

// Decap admin shell — generated by decapAdminHtml(), no build step required.
// CDN loads Decap CMS + Laika backend; no public/admin bundle to maintain.
app.get('/admin', c => c.html(ADMIN_HTML));

// Blog homepage — list published posts via laika.documents.
app.get('/', async c => {
  const { items: records } = await collectStream(
    laika.documents.listRecordSummaries({
      pagination: { page: 1, perPage: 100 },
      folder: 'posts',
      depth: 1,
      type: 'published',
    }),
  );

  const posts = records
    .filter(r => r.type === 'published-summary')
    .sort((a, b) => {
      if (a.updatedAt && b.updatedAt) return b.updatedAt.localeCompare(a.updatedAt);
      return b.key.localeCompare(a.key);
    });

  const items = posts
    .map(post => {
      const slug = post.key.replace(/^posts\//, '').replace(/\.md$/, '');
      const date = post.updatedAt
        ? ` · <time>${new Date(post.updatedAt).toLocaleDateString()}</time>`
        : '';
      return `<li style="margin-bottom:1rem"><a href="/blog/${escHtml(slug)}">${escHtml(slug)}</a>${date}</li>`;
    })
    .join('\n');

  const body = posts.length === 0
    ? '<p>No posts yet. <a href="/admin">Open the CMS</a> to write your first post.</p>'
    : `<ul style="list-style:none;padding:0">${items}</ul>`;

  return c.html(page('My Blog', `<h1>My Blog</h1>${body}`));
});

// Individual blog post.
app.get('/blog/:slug', async c => {
  const slug = c.req.param('slug');

  let post;
  try {
    post = await runTask(laika.documents.getDocument(`posts/${slug}`));
  } catch {
    return c.notFound();
  }

  const { title, date, description, body } = post.content as {
    title?: string,
    date?: string,
    description?: string,
    body?: string,
  };

  const html = `
    <article>
      <h1>${escHtml(title ?? slug)}</h1>
      ${date ? `<time style="color:#666">${new Date(date).toLocaleDateString()}</time>` : ''}
      ${description ? `<p><em>${escHtml(description)}</em></p>` : ''}
      <pre style="white-space:pre-wrap;font-family:inherit">${escHtml(body ?? '')}</pre>
      <p><a href="/">← Back</a></p>
    </article>`;

  return c.html(page(title ?? slug, html));
});

// Static files from public/ — media uploads, etc.
// Bun.file() returns a Blob; passing it to Response streams efficiently.
app.use('/*', async c => {
  const pathname = c.req.path;
  const resolved = pathname.endsWith('/')
    ? join(PUBLIC_DIR, pathname, 'index.html')
    : join(PUBLIC_DIR, pathname);

  if (!resolved.startsWith(PUBLIC_DIR)) return c.notFound();

  const file = Bun.file(resolved);
  if (!(await file.exists())) return c.notFound();

  const ext = resolved.slice(resolved.lastIndexOf('.')).toLowerCase();
  const contentType = MIME[ext] ?? 'application/octet-stream';

  return new Response(file, { headers: { 'Content-Type': contentType } });
});

const PORT = Number(process.env.PORT ?? 3000);

Bun.serve({ fetch: app.fetch, port: PORT });

console.log(`Hono/Bun blog running at http://localhost:${PORT}`);
console.log(`  Blog:  http://localhost:${PORT}/`);
console.log(`  Admin: http://localhost:${PORT}/admin`);
