#!/usr/bin/env bash
#
# One-time Cloudflare Tunnel setup for the remote test session.
#
# Installs cloudflared if needed, logs you into Cloudflare, creates a named
# tunnel, writes the ingress config, and points DNS for the two hostnames at
# the tunnel. Safe to re-run — every step is idempotent.
#
# After this, run setup-access.sh (or configure Access by hand) to put the
# login wall in front, then use start.sh to go live.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_ENV="$HERE/config.env"

if [[ ! -f "$CONFIG_ENV" ]]; then
  echo "✗ Missing $CONFIG_ENV"
  echo "  Run: cp $HERE/config.example.env $CONFIG_ENV  and fill it in."
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_ENV"

: "${TUNNEL_NAME:?set TUNNEL_NAME in config.env}"
: "${APP_HOSTNAME:?set APP_HOSTNAME in config.env}"
: "${GATEWAY_HOSTNAME:?set GATEWAY_HOSTNAME in config.env}"
: "${APP_PORT:=3200}"
: "${GATEWAY_PORT:=8787}"

# 1. Install cloudflared.
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "→ cloudflared not found; installing via Homebrew…"
  brew install cloudflared
fi
echo "✓ cloudflared $(cloudflared --version 2>/dev/null | head -1)"

# 2. Authenticate (opens a browser; pick the zone for your domain).
CERT="${HOME}/.cloudflared/cert.pem"
if [[ ! -f "$CERT" ]]; then
  echo "→ Logging into Cloudflare (a browser window will open)…"
  cloudflared tunnel login
fi
echo "✓ Cloudflare login present ($CERT)"

# 3. Create the named tunnel if it doesn't already exist.
if cloudflared tunnel list -o json | grep -q "\"name\":\"${TUNNEL_NAME}\""; then
  echo "✓ Tunnel '${TUNNEL_NAME}' already exists"
else
  echo "→ Creating tunnel '${TUNNEL_NAME}'…"
  cloudflared tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID="$(cloudflared tunnel list -o json \
  | python3 -c "import sys,json;print(next(t['id'] for t in json.load(sys.stdin) if t['name']=='${TUNNEL_NAME}'))")"
CREDS="${HOME}/.cloudflared/${TUNNEL_ID}.json"
echo "✓ Tunnel id ${TUNNEL_ID}"

# 4. Write the ingress config used by start.sh.
CONFIG_YML="$HERE/cloudflared.yml"
cat > "$CONFIG_YML" <<YAML
# Generated by setup-tunnel.sh — maps public hostnames to local dev servers.
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS}
ingress:
  - hostname: ${APP_HOSTNAME}
    service: http://localhost:${APP_PORT}
  - hostname: ${GATEWAY_HOSTNAME}
    service: http://localhost:${GATEWAY_PORT}
  - service: http_status:404
YAML
echo "✓ Wrote ${CONFIG_YML}"

# 5. Point DNS at the tunnel (idempotent — re-running just confirms).
echo "→ Routing DNS…"
cloudflared tunnel route dns "$TUNNEL_NAME" "$APP_HOSTNAME" || true
cloudflared tunnel route dns "$TUNNEL_NAME" "$GATEWAY_HOSTNAME" || true

cat <<DONE

✓ Tunnel ready.
  App:     https://${APP_HOSTNAME}   → localhost:${APP_PORT}
  Gateway: https://${GATEWAY_HOSTNAME} → localhost:${GATEWAY_PORT}

Next:
  1. Put the login wall in front:  scripts/remote-session/setup-access.sh
     (or configure it by hand — see scripts/remote-session/README.md)
  2. Set the GitHub App OAuth callback to:
        https://${APP_HOSTNAME}/auth/callback
  3. Go live:  scripts/remote-session/start.sh
DONE
