import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitepress';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Generated by scripts/generate-api-docs.mjs (TypeDoc), which the docs package's `dev`/`build`
// scripts always run first. Falls back to an empty list so `vitepress dev`/`build` invoked directly
// (skipping that step) doesn't crash — it just won't list the API modules. Only the
// module links are kept: VitePress inlines the whole sidebar into every page, and the full
// per-symbol tree (~800 entries) made each page ~570 KB. Module index pages list their members.
type SidebarNode = { text: string, link?: string, items?: SidebarNode[] };
const apiSidebarFile = resolve(__dirname, '..', 'reference', 'api', 'typedoc-sidebar.json');
// Module (and namespace) index pages are the links ending in `/`; symbol pages end in `.md`.
// Labels are rebuilt from the tree, not the link: page paths drop the `@laikacms/` scope. A node
// without a link is a path segment shared by several modules (`laikacms` > `core`), except the
// `Namespaces` group, whose children join with `.` (`laikacms/core.LaikaTask`).
const apiIndexItems = (nodes: SidebarNode[], prefix = '', separator = '/'): { text: string, link: string }[] =>
  nodes.flatMap(node => {
    const name = prefix ? `${prefix}${separator}${node.text}` : node.text;
    if (node.link?.endsWith('/')) return [{ text: name, link: node.link }, ...apiIndexItems(node.items ?? [], name)];
    if (node.link) return [];
    return node.text === 'Namespaces'
      ? apiIndexItems(node.items ?? [], prefix, '.')
      : apiIndexItems(node.items ?? [], name);
  });
const apiSidebarItems = existsSync(apiSidebarFile)
  ? apiIndexItems(JSON.parse(readFileSync(apiSidebarFile, 'utf8')))
  : [];

// Generated from the root adapters.yaml by scripts/generate-adapter-docs.mjs, which `dev`/`build`
// run first. Empty when that step was skipped.
const adapterSidebarFile = resolve(__dirname, 'adapters', 'sidebar.json');
// Sidebar text is HTML, so the logos (light + dark; custom.css shows one) need the base path.
const base = '/docs/';
const adapterSidebarItems = existsSync(adapterSidebarFile)
  ? (JSON.parse(readFileSync(adapterSidebarFile, 'utf8')) as { key: string, text: string, link: string }[]).map(
    ({ key, text, link }) => ({
      text: `<img class="adapter-icon adapter-icon-light" src="${base}adapters/${key}.svg" alt="">`
        + `<img class="adapter-icon adapter-icon-dark" src="${base}adapters/${key}-dark.svg" alt="">${text}`,
      link,
    }),
  )
  : [];

const websiteUrl = 'https://laikacms.com/';

export default defineConfig({
  title: 'Laika',
  description: 'A modular, runtime-agnostic content API for your own custom or existing UIs.',
  // Served at laikacms.com/docs/ alongside the marketing site (see the
  // laika-cloud repo, ADR-0028). `pnpm build:site` at the workspace root
  // assembles apps/website/dist + this dist into one Cloudflare Pages deploy.
  base,
  cleanUrls: true,
  // Keep the page-hash map and site data in one shared chunk instead of inlining it into every
  // HTML page; with the generated API reference (~800 pages) it would otherwise dominate each page.
  metaChunk: true,
  lastUpdated: true,
  markdown: {
    // ```mermaid fences become the raw diagram source; theme/mermaid.ts renders them client-side.
    config: md => {
      const fence = md.renderer.rules.fence!;
      md.renderer.rules.fence = (tokens, idx, options, env, self) => {
        const token = tokens[idx];
        if (token.info.trim() !== 'mermaid') return fence(tokens, idx, options, env, self);
        return `<pre class="mermaid" v-pre>${md.utils.escapeHtml(token.content)}</pre>\n`;
      };
    },
  },
  // The apps/ tree was moved out of the monorepo (June 2026).
  // Any lingering ../apps/ references point at external source dirs, not vitepress pages.
  ignoreDeadLinks: [/\/apps\//],
  // Same typefaces as apps/website: Archivo (display), IBM Plex Sans (body), IBM Plex Mono (code).
  head: [
    ['link', { rel: 'icon', href: '/docs/laika-icon.png' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    [
      'link',
      {
        rel: 'stylesheet',
        href:
          'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;450;500;600&family=IBM+Plex+Mono:wght@400;500&family=Archivo:wght@400;500;600;700&display=swap',
      },
    ],
  ],
  themeConfig: {
    // The website's lockup: round icon + "Laika".
    logo: '/laika-icon.png',
    siteTitle: 'Laika',
    // The site title leads back to the marketing site, not the docs root. Absolute URL on purpose:
    // root-relative links get the `/docs/` base prepended.
    logoLink: { link: websiteUrl, target: '_self' },
    nav: [
      { text: 'Website', link: websiteUrl, target: '_self', noIcon: true },
      { text: 'Get Started', link: '/guides/getting-started', activeMatch: '/guides/' },
      { text: 'Adapters', link: '/adapters/', activeMatch: '/adapters/' },
      { text: 'Concepts', link: '/concepts/', activeMatch: '/concepts/' },
      { text: 'Reference', link: '/reference/json-api/', activeMatch: '/reference/' },
      { text: 'Contributing', link: '/contributing/', activeMatch: '/contributing/' },
    ],
    sidebar: [
      { text: 'Introduction', link: '/' },
      {
        text: 'Get Started',
        items: [
          { text: 'Overview', link: '/guides/' },
          { text: 'Getting Started', link: '/guides/getting-started' },
          { text: 'API Server', link: '/guides/api-server' },
        ],
      },
      {
        text: 'Adapters',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/adapters/' },
          ...adapterSidebarItems,
          { text: 'Writing your own', link: '/adapters/#writing-your-own' },
        ],
      },
      {
        text: 'Integrations',
        items: [
          { text: 'Astro', link: '/guides/astro' },
          { text: 'Vite', link: '/guides/vite' },
          {
            text: 'Decap CMS',
            collapsed: true,
            items: [
              { text: 'Overview', link: '/guides/decap/' },
              { text: 'The decap-cms Fork', link: '/guides/decap/fork' },
              { text: 'Quickstart: FileSystem + Decap', link: '/guides/decap/quickstart-fs' },
              { text: 'Local Mode Dev Editing', link: '/guides/decap/local-mode' },
              { text: 'Standalone Worker', link: '/guides/decap/standalone-worker' },
              { text: 'Serving the Admin Shell', link: '/guides/decap/admin-shell' },
              { text: 'Authentication', link: '/guides/decap/auth' },
              { text: 'Widgets & Editor Components', link: '/guides/decap/widgets-and-editors' },
              { text: 'AI Assistant', link: '/guides/ai-assistant' },
              { text: 'Git Gateway', link: '/guides/decap/git-gateway' },
              { text: 'Framework Setup Notes', link: '/guides/decap/frameworks' },
            ],
          },
        ],
      },
      {
        text: 'Concepts',
        items: [
          { text: 'Overview', link: '/concepts/' },
          { text: 'Architecture', link: '/concepts/architecture' },
          { text: 'Repositories', link: '/concepts/repositories' },
          { text: 'Content Model', link: '/concepts/content-model' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'Overview', link: '/reference/' },
          {
            text: 'JSON:API',
            collapsed: false,
            items: [
              { text: 'Overview', link: '/reference/json-api/' },
              { text: 'Storage API', link: '/reference/json-api/storage' },
              { text: 'Documents API', link: '/reference/json-api/documents' },
              { text: 'Assets API', link: '/reference/json-api/assets' },
              { text: 'Catalog API', link: '/reference/json-api/catalog' },
              { text: 'Error Responses', link: '/reference/json-api/errors' },
              {
                text: 'OpenAPI Reference',
                collapsed: true,
                items: [
                  { text: 'Storage API', link: '/reference/json-api/openapi-storage' },
                  { text: 'Documents API', link: '/reference/json-api/openapi-documents' },
                  { text: 'Assets API', link: '/reference/json-api/openapi-assets' },
                  { text: 'Catalog API', link: '/reference/json-api/openapi-catalog' },
                ],
              },
            ],
          },
          { text: 'Imports', link: '/reference/imports' },
          { text: 'CLI', link: '/reference/cli' },
          {
            text: 'TypeScript API',
            collapsed: true,
            items: [
              { text: 'Overview', link: '/reference/api/' },
              ...apiSidebarItems,
            ],
          },
          { text: 'Glossary', link: '/reference/glossary' },
        ],
      },
      {
        text: 'Contributing',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/contributing/' },
          { text: 'Local Setup', link: '/contributing/local-setup' },
          { text: 'Inner Loop', link: '/contributing/inner-loop' },
          { text: 'Landing a PR', link: '/contributing/landing-a-pr' },
          { text: 'House Style', link: '/contributing/house-style' },
          { text: 'Starter Templates', link: '/contributing/starters' },
        ],
      },
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/laikacms/laikacms' }],
    search: { provider: 'local' },
    editLink: {
      pattern: 'https://github.com/laikacms/laikacms/edit/develop/docs/:path',
      text: 'Edit this page on GitHub',
    },
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © Laika contributors',
    },
  },
});
