import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitepress';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Generated by scripts/aggregate-package-docs.mjs (LCMS-454), which the docs
// package's `dev`/`build` scripts always run first. Falls back to an empty
// list so `vitepress dev`/`build` invoked directly (skipping that step)
// doesn't crash — it just won't show package reference pages.
const packageSidebarFile = resolve(__dirname, 'generated', 'package-sidebar.json');
const packageSidebarItems = existsSync(packageSidebarFile)
  ? JSON.parse(readFileSync(packageSidebarFile, 'utf8'))
  : [];

export default defineConfig({
  title: 'Laika CMS',
  description:
    'The self-hosted content API: Git, S3, SQL, or Obsidian as the backend, Decap CMS as the editor, running anywhere fetch runs.',
  // Served at laikacms.com/docs/ alongside the marketing site (see the
  // laika-cloud repo, ADR-0028). `pnpm build:site` at the workspace root
  // assembles apps/website/dist + this dist into one Cloudflare Pages deploy.
  base: '/docs/',
  cleanUrls: true,
  lastUpdated: true,
  // The apps/ tree was moved out of the monorepo (June 2026).
  // Any lingering ../apps/ references point at external source dirs, not vitepress pages.
  ignoreDeadLinks: [/\/apps\//],
  themeConfig: {
    nav: [
      { text: 'Get Started', link: '/getting-started/vite', activeMatch: '/getting-started/' },
      { text: 'Concepts', link: '/concepts/motivation', activeMatch: '/concepts/' },
      { text: 'Decap CMS', link: '/decap/', activeMatch: '/decap/' },
      { text: 'Reference', link: '/reference/json-api/', activeMatch: '/reference/' },
    ],
    sidebar: [
      {
        text: 'Getting Started',
        items: [
          { text: 'Quickstart: Vite', link: '/getting-started/vite' },
          { text: 'Quickstart: Next.js', link: '/getting-started/nextjs' },
          { text: 'Quickstart: Node.js', link: '/getting-started/nodejs' },
          { text: 'Quickstart: Cloudflare Workers', link: '/getting-started/cloudflare-workers' },
          { text: 'Quickstart: Vercel', link: '/getting-started/vercel' },
          { text: 'Starters', link: '/getting-started/starters' },
          { text: 'Deploy to Production', link: '/getting-started/deploy' },
        ],
      },
      {
        text: 'Decap CMS',
        items: [
          { text: 'Overview', link: '/decap/' },
          { text: 'Configuration', link: '/decap/configuration' },
          { text: 'Authentication', link: '/decap/auth' },
          { text: 'Serving the Admin Shell', link: '/decap/admin-shell' },
          { text: 'Widgets & Editor Components', link: '/decap/widgets-and-editors' },
          { text: 'Standalone Worker', link: '/decap/standalone-worker' },
        ],
      },
      {
        text: 'Concepts',
        items: [
          { text: 'Motivation', link: '/concepts/motivation' },
          { text: 'Architecture', link: '/concepts/architecture' },
          {
            text: 'Protocols',
            items: [
              { text: 'Storage', link: '/concepts/storage' },
              { text: 'Documents', link: '/concepts/documents' },
              { text: 'Assets', link: '/concepts/assets' },
              { text: 'Catalog', link: '/concepts/catalog' },
            ],
          },
          { text: 'Transports', link: '/concepts/transports' },
        ],
      },
      {
        text: 'Backends',
        collapsed: false,
        items: [
          {
            text: 'Git hosts',
            items: [
              { text: 'GitHub', link: '/backends/github' },
              { text: 'GitLab', link: '/backends/gitlab' },
              { text: 'Bitbucket', link: '/backends/bitbucket' },
            ],
          },
          {
            text: 'Object storage',
            items: [
              { text: 'S3 (and compatibles)', link: '/backends/s3' },
              { text: 'Cloudflare R2', link: '/backends/r2' },
            ],
          },
          {
            text: 'Databases',
            items: [
              { text: 'SQL (Drizzle)', link: '/backends/sql' },
              { text: 'DynamoDB', link: '/backends/dynamodb' },
            ],
          },
          {
            text: 'Filesystem & browser',
            items: [
              { text: 'FileSystem', link: '/backends/fs' },
              { text: 'Browser FS (OPFS)', link: '/backends/opfs' },
              { text: 'Web Storage', link: '/backends/web' },
            ],
          },
          {
            text: 'Other',
            items: [
              { text: 'WebDAV', link: '/backends/webdav' },
              { text: 'Obsidian', link: '/backends/obsidian' },
              { text: 'JSON:API Proxy', link: '/backends/jsonapi-proxy' },
              { text: 'GitHub CDN', link: '/backends/github-cdn' },
            ],
          },
        ],
      },
      {
        text: 'Serializers',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/serializers/' },
          { text: 'JSON', link: '/serializers/json' },
          { text: 'Markdown', link: '/serializers/markdown' },
          { text: 'YAML', link: '/serializers/yaml' },
          { text: 'Raw', link: '/serializers/raw' },
          { text: 'Write Your Own', link: '/serializers/custom' },
        ],
      },
      {
        text: 'Middleware',
        items: [
          { text: 'API', link: '/middleware/api' },
          { text: 'OAuth2', link: '/middleware/oauth2' },
        ],
      },
      {
        text: 'CLI',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/cli/' },
          { text: 'create', link: '/cli/create' },
          { text: 'local serve', link: '/cli/serve' },
          { text: 'local generate', link: '/cli/generate' },
          { text: 'local migrate', link: '/cli/migrate' },
        ],
      },
      {
        text: 'Reference',
        items: [
          {
            text: 'JSON:API',
            collapsed: false,
            items: [
              { text: 'Overview', link: '/reference/json-api/' },
              { text: 'Storage API', link: '/reference/json-api/storage' },
              { text: 'Documents API', link: '/reference/json-api/documents' },
              { text: 'Assets API', link: '/reference/json-api/assets' },
              { text: 'Catalog API', link: '/reference/json-api/catalog' },
              { text: 'Error Responses', link: '/reference/json-api/errors' },
            ],
          },
          {
            text: 'Packages',
            collapsed: true,
            items: [
              { text: 'Overview', link: '/reference/packages' },
              ...packageSidebarItems,
            ],
          },
          { text: 'Glossary', link: '/reference/glossary' },
        ],
      },
      {
        text: 'Contributing',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/contributing/' },
          { text: 'Local Setup', link: '/contributing/local-setup' },
          { text: 'Inner Loop', link: '/contributing/inner-loop' },
          { text: 'Landing a PR', link: '/contributing/landing-a-pr' },
          { text: 'House Style', link: '/contributing/house-style' },
          { text: 'Package Reference Docs', link: '/contributing/package-docs' },
          { text: 'Starter Templates', link: '/contributing/starters' },
        ],
      },
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/laikacms/laikacms' }],
    search: { provider: 'local' },
    editLink: {
      pattern: 'https://github.com/laikacms/laikacms/edit/develop/docs/:path',
      text: 'Edit this page on GitHub',
    },
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © Laika CMS contributors',
    },
  },
});
