/**
 * LaikaCMS admin sidecar for the Lume SSG starter.
 *
 * Lume is a static site generator — it has no runtime request handler.
 * The Jamstack sidecar pattern runs two processes side-by-side:
 *
 *   pnpm site:dev  → Lume dev server on port 4000 (generated HTML)
 *   pnpm admin:dev → this Hono server on port 3001 (Decap CMS + API)
 *
 * When the Decap editor saves a file via the Laika API, LaikaCMS writes
 * it to src/posts/. Lume watches src/ and rebuilds automatically.
 *
 * Note: Deno.serve() gives a WHATWG Request directly, so Hono's c.req.raw
 * is zero-adaptation — no IncomingMessage bridge needed.
 */
import { Hono } from '@hono/hono';
import { serveStatic } from '@hono/hono/deno';

import { ADMIN_HTML, laika } from './laika.ts';

const PORT = Number(Deno.env.get('PORT') ?? 3001);

const app = new Hono();

// Decap admin UI — generated by decapAdminHtml() (no esbuild needed).
app.get('/admin', c => c.html(ADMIN_HTML));
app.get('/admin/', c => c.html(ADMIN_HTML));

// Decap JSON:API — Deno's native fetch handler means c.req.raw is a WHATWG
// Request; pass directly to laika.fetch with zero adaptation.
app.all('/api/decap/*', c => laika.fetch(c.req.raw));

// Serve uploaded media files from src/uploads/.
app.use('/uploads/*', serveStatic({ root: '../src', rewriteRequestPath: p => p }));

const server = Deno.serve({ port: PORT }, app.fetch);

console.log(`LaikaCMS admin → http://localhost:${PORT}/admin`);
console.log(`Laika API      → http://localhost:${PORT}/api/decap`);
console.log(`Lume site      → http://localhost:4000 (run pnpm site:dev)`);
