import type { Collection, State, Collections } from '../types/redux';
import type { AnyAction } from 'redux';
import type { Status } from '../constants/publishModes';
import type { ThunkDispatch } from 'redux-thunk';
export declare const UNPUBLISHED_ENTRY_REQUEST = "UNPUBLISHED_ENTRY_REQUEST";
export declare const UNPUBLISHED_ENTRY_SUCCESS = "UNPUBLISHED_ENTRY_SUCCESS";
export declare const UNPUBLISHED_ENTRY_REDIRECT = "UNPUBLISHED_ENTRY_REDIRECT";
export declare const UNPUBLISHED_ENTRIES_REQUEST = "UNPUBLISHED_ENTRIES_REQUEST";
export declare const UNPUBLISHED_ENTRIES_SUCCESS = "UNPUBLISHED_ENTRIES_SUCCESS";
export declare const UNPUBLISHED_ENTRIES_FAILURE = "UNPUBLISHED_ENTRIES_FAILURE";
export declare const UNPUBLISHED_ENTRY_PERSIST_REQUEST = "UNPUBLISHED_ENTRY_PERSIST_REQUEST";
export declare const UNPUBLISHED_ENTRY_PERSIST_SUCCESS = "UNPUBLISHED_ENTRY_PERSIST_SUCCESS";
export declare const UNPUBLISHED_ENTRY_PERSIST_FAILURE = "UNPUBLISHED_ENTRY_PERSIST_FAILURE";
export declare const UNPUBLISHED_ENTRY_STATUS_CHANGE_REQUEST = "UNPUBLISHED_ENTRY_STATUS_CHANGE_REQUEST";
export declare const UNPUBLISHED_ENTRY_STATUS_CHANGE_SUCCESS = "UNPUBLISHED_ENTRY_STATUS_CHANGE_SUCCESS";
export declare const UNPUBLISHED_ENTRY_STATUS_CHANGE_FAILURE = "UNPUBLISHED_ENTRY_STATUS_CHANGE_FAILURE";
export declare const UNPUBLISHED_ENTRY_PUBLISH_REQUEST = "UNPUBLISHED_ENTRY_PUBLISH_REQUEST";
export declare const UNPUBLISHED_ENTRY_PUBLISH_SUCCESS = "UNPUBLISHED_ENTRY_PUBLISH_SUCCESS";
export declare const UNPUBLISHED_ENTRY_PUBLISH_FAILURE = "UNPUBLISHED_ENTRY_PUBLISH_FAILURE";
export declare const UNPUBLISHED_ENTRY_DELETE_REQUEST = "UNPUBLISHED_ENTRY_DELETE_REQUEST";
export declare const UNPUBLISHED_ENTRY_DELETE_SUCCESS = "UNPUBLISHED_ENTRY_DELETE_SUCCESS";
export declare const UNPUBLISHED_ENTRY_DELETE_FAILURE = "UNPUBLISHED_ENTRY_DELETE_FAILURE";
export declare function loadUnpublishedEntry(collection: Collection, slug: string): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => Promise<void>;
export declare function loadUnpublishedEntries(collections: Collections): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => void;
export declare function persistUnpublishedEntry(collection: Collection, existingUnpublishedEntry: boolean): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => Promise<any>;
export declare function updateUnpublishedEntryStatus(collection: string, slug: string, oldStatus: Status, newStatus: Status): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => void;
export declare function deleteUnpublishedEntry(collection: string, slug: string): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => any;
export declare function publishUnpublishedEntry(collectionName: string, slug: string): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => Promise<any>;
export declare function unpublishPublishedEntry(collection: Collection, slug: string): (dispatch: ThunkDispatch<State, {}, AnyAction>, getState: () => State) => Promise<void>;
