// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $admin from './routes/admin.tsx';
import * as $api_decap_path_ from './routes/api/decap/[...path].ts';
import * as $blog_slug_ from './routes/blog/[slug].tsx';
import * as $index from './routes/index.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest: Manifest = {
  routes: {
    './routes/admin.tsx': $admin,
    './routes/api/decap/[...path].ts': $api_decap_path_,
    './routes/blog/[slug].tsx': $blog_slug_,
    './routes/index.tsx': $index,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
