/**
 * CMS registration module — generated by the `laika create` wizard.
 *
 * Boots the bare, non-laika Decap app (`@laikacms/decap-cms/app/bare`), which
 * ships with no backends, widgets, or locales; everything the admin
 * uses is registered explicitly below. Re-run the wizard or edit this file
 * to change the selection. English is always registered as the fallback.
*/
import { DecapCmsApp as CMS, init } from '@laikacms/decap-cms/app/bare';
import en from '@laikacms/decap-cms/locales/en';

import createLaikaBackend from '@laikacms/decap-cms/backends/laika';
import DecapCmsWidgetString from '@laikacms/decap-cms/widgets/string';
import DecapCmsWidgetDatetime from '@laikacms/decap-cms/widgets/datetime';
import { markdownFormat } from '@laikacms/decap-cms/format-packs/markdown';
import { passthroughSerializer, Widget as RichtextWidget } from '@laikacms/decap-cms/widgets/richtext';

CMS.registerLocale('en', en);

CMS.registerBackend('laika', createLaikaBackend());

CMS.registerWidget(DecapCmsWidgetString.Widget());
CMS.registerWidget(DecapCmsWidgetDatetime.Widget());
// Spread: interfaces lack the implicit index signature registerWidget expects
const richtextWidget = { ...RichtextWidget() };
CMS.registerWidget(richtextWidget);
CMS.registerWidget({ ...richtextWidget, name: 'markdown' });
CMS.registerWidgetValueSerializer('richtext', passthroughSerializer);
CMS.registerWidgetValueSerializer('markdown', passthroughSerializer);
CMS.registerRichtextFormat(markdownFormat);

export { CMS, init };
