/**
 * Side-effect import: registers every bundled `Mapper` so `RichtextValue`
 * and `detectMapper` work as soon as the widget is loaded.
 *
 * Same registry as the Lexical widget — the mappers are editor-agnostic
 * and live in a global singleton, so either widget can be loaded in the
 * same page without conflict.
 */
import { registerMapper } from '@laikacloud/portabletext-core';
import { adaptiveCardsFormat } from 'portable-text-to-adaptive-cards-mapper';
import { ansiFormat } from 'portable-text-to-ansi-mapper';
import { asciiDocFormat } from 'portable-text-to-asciidoc-mapper';
import { bbcodeFormat } from 'portable-text-to-bbcode-mapper';
import { bibtexFormat } from 'portable-text-to-bibtex-mapper';
import { confluenceStorageFormat } from 'portable-text-to-confluence-storage-mapper';
import { contentfulRtfFormat } from 'portable-text-to-contentful-rtf-mapper';
import { creoleFormat } from 'portable-text-to-creole-mapper';
import { discordFormat } from 'portable-text-to-discord-mapper';
import { ditaFormat } from 'portable-text-to-dita-mapper';
import { docbookFormat } from 'portable-text-to-docbook-mapper';
import { dokuwikiFormat } from 'portable-text-to-dokuwiki-mapper';
import { editorJsFormat } from 'portable-text-to-editorjs-mapper';
import { fb2Format } from 'portable-text-to-fb2-mapper';
import { fountainFormat } from 'portable-text-to-fountain-mapper';
import { gemtextFormat } from 'portable-text-to-gemtext-mapper';
import { gutenbergFormat } from 'portable-text-to-gutenberg-mapper';
import { hamlFormat } from 'portable-text-to-haml-mapper';
import { htmlFormat } from 'portable-text-to-html-mapper';
import { icmlFormat } from 'portable-text-to-icml-mapper';
import { ircFormat } from 'portable-text-to-irc-mapper';
import { jatsFormat } from 'portable-text-to-jats-mapper';
import { jiraFormat } from 'portable-text-to-jira-mapper';
import { jupyterFormat } from 'portable-text-to-jupyter-mapper';
import { jupytextFormat } from 'portable-text-to-jupytext-mapper';
import { latexFormat } from 'portable-text-to-latex-mapper';
import { logseqFormat } from 'portable-text-to-logseq-mapper';
import { markdocFormat } from 'portable-text-to-markdoc-mapper';
import { markdownFormat } from 'portable-text-to-markdown-mapper';
import { markuaFormat } from 'portable-text-to-markua-mapper';
import { mdxFormat } from 'portable-text-to-mdx-mapper';
import { mediaWikiFormat } from 'portable-text-to-mediawiki-mapper';
import { moinMoinFormat } from 'portable-text-to-moinmoin-mapper';
import { mystFormat } from 'portable-text-to-myst-mapper';
import { notionFormat } from 'portable-text-to-notion-mapper';
import { obsidianFormat } from 'portable-text-to-obsidian-mapper';
import { ooxmlFormat } from 'portable-text-to-ooxml-mapper';
import { orgmodeFormat } from 'portable-text-to-orgmode-mapper';
import { pandocJsonFormat } from 'portable-text-to-pandoc-json-mapper';
import { pandocFormat } from 'portable-text-to-pandoc-mapper';
import { plainTextFormat } from 'portable-text-to-plaintext-mapper';
import { podFormat } from 'portable-text-to-pod-mapper';
import { pollenFormat } from 'portable-text-to-pollen-mapper';
import { portableTextFormat } from 'portable-text-to-portabletext-mapper';
import { proseMirrorFormat } from 'portable-text-to-prosemirror-mapper';
import { pugFormat } from 'portable-text-to-pug-mapper';
import { quartoFormat } from 'portable-text-to-quarto-mapper';
import { quillFormat } from 'portable-text-to-quill-mapper';
import { roffFormat } from 'portable-text-to-roff-mapper';
import { rstFormat } from 'portable-text-to-rst-mapper';
import { rtfFormat } from 'portable-text-to-rtf-mapper';
import { setextFormat } from 'portable-text-to-setext-mapper';
import { slackBlocksFormat } from 'portable-text-to-slack-blocks-mapper';
import { slackFormat } from 'portable-text-to-slack-mapper';
import { slateFormat } from 'portable-text-to-slate-mapper';
import { teiFormat } from 'portable-text-to-tei-mapper';
import { telegramFormat } from 'portable-text-to-telegram-mapper';
import { texinfoFormat } from 'portable-text-to-texinfo-mapper';
import { textileFormat } from 'portable-text-to-textile-mapper';
import { tiddlyWikiFormat } from 'portable-text-to-tiddlywiki-mapper';
import { tracFormat } from 'portable-text-to-trac-mapper';
import { twikiFormat } from 'portable-text-to-twiki-mapper';
import { txt2tagsFormat } from 'portable-text-to-txt2tags-mapper';
import { typstFormat } from 'portable-text-to-typst-mapper';
import { vimwikiFormat } from 'portable-text-to-vimwiki-mapper';
import { whatsappFormat } from 'portable-text-to-whatsapp-mapper';
import { wikidotFormat } from 'portable-text-to-wikidot-mapper';
import { zimFormat } from 'portable-text-to-zim-mapper';

let registered = false;

export function ensureDefaultMappersRegistered(): void {
  if (registered) return;
  registered = true;
  registerMapper(markdownFormat);
  registerMapper(htmlFormat);
  registerMapper(portableTextFormat);
  registerMapper(contentfulRtfFormat);
  registerMapper(plainTextFormat);
  registerMapper(bbcodeFormat);
  registerMapper(mediaWikiFormat);
  registerMapper(asciiDocFormat);
  registerMapper(orgmodeFormat);
  registerMapper(textileFormat);
  registerMapper(gemtextFormat);
  registerMapper(rstFormat);
  registerMapper(latexFormat);
  registerMapper(slackFormat);
  registerMapper(discordFormat);
  registerMapper(jiraFormat);
  registerMapper(obsidianFormat);
  registerMapper(podFormat);
  registerMapper(dokuwikiFormat);
  registerMapper(roffFormat);
  registerMapper(tiddlyWikiFormat);
  registerMapper(telegramFormat);
  registerMapper(creoleFormat);
  registerMapper(texinfoFormat);
  registerMapper(whatsappFormat);
  registerMapper(mdxFormat);
  registerMapper(mystFormat);
  registerMapper(tracFormat);
  registerMapper(twikiFormat);
  registerMapper(setextFormat);
  registerMapper(markdocFormat);
  registerMapper(docbookFormat);
  registerMapper(pugFormat);
  registerMapper(proseMirrorFormat);
  registerMapper(pandocFormat);
  registerMapper(editorJsFormat);
  registerMapper(quillFormat);
  registerMapper(slateFormat);
  registerMapper(moinMoinFormat);
  registerMapper(fountainFormat);
  registerMapper(notionFormat);
  registerMapper(hamlFormat);
  registerMapper(typstFormat);
  registerMapper(bibtexFormat);
  registerMapper(txt2tagsFormat);
  registerMapper(fb2Format);
  registerMapper(markuaFormat);
  registerMapper(ditaFormat);
  registerMapper(jatsFormat);
  registerMapper(teiFormat);
  registerMapper(rtfFormat);
  registerMapper(confluenceStorageFormat);
  registerMapper(quartoFormat);
  registerMapper(logseqFormat);
  registerMapper(zimFormat);
  registerMapper(ansiFormat);
  registerMapper(pollenFormat);
  registerMapper(vimwikiFormat);
  registerMapper(wikidotFormat);
  registerMapper(ircFormat);
  registerMapper(jupyterFormat);
  registerMapper(ooxmlFormat);
  registerMapper(icmlFormat);
  registerMapper(pandocJsonFormat);
  registerMapper(jupytextFormat);
  registerMapper(gutenbergFormat);
  registerMapper(adaptiveCardsFormat);
  registerMapper(slackBlocksFormat);
}

ensureDefaultMappersRegistered();
